Vagrant.configure("2") do |config|

config.vm.define "ansible" do |ansible|
  ansible.vm.box = "generic/debian12"
  ansible.vm.network "public_network"
  ansible.vm.network "private_network", ip: "192.168.50.51", virtualbox__intnet: "ansible_lab"
  ansible.vm.hostname = "ansible-kmasing"
  ansible.vm.synced_folder "./ansible_data", "/vagrant_data"
  ansible.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "2048"]
    vb.customize ["modifyvm", :id, "--cpus", "2"]
	vb.name = "ANSIBLE"
    end
  ansible.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y git ansible
    apt-get install fish
    apt-get install tmux
    apt-get install mc
    apt-get install git
	
  SHELL
  end
config.vm.define "ubuntu" do |ubuntu|
  ubuntu.vm.box = "generic/ubuntu2304"
  ubuntu.vm.network "public_network"
  ubuntu.vm.network "private_network", ip: "192.168.50.53", virtualbox__intnet: "ansible_lab"
  ubuntu.vm.hostname = "ubuntu-kmasing"
  ubuntu.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "2048"]
    vb.customize ["modifyvm", :id, "--cpus", "2"]
	vb.name = "UBUNTU"
    end
  ubuntu.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y git
    apt-get install fish
    apt-get install tmux
    apt-get install mc
    apt-get install git
   SHELL

  end
config.vm.define "debian" do |debian|
  debian.vm.box = "generic/debian12"
  debian.vm.network "public_network"
  debian.vm.network "private_network", ip: "192.168.50.52", virtualbox__intnet: "ansible_lab"
  debian.vm.hostname = "debian-kmasing"
  debian.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "2048"]
    vb.customize ["modifyvm", :id, "--cpus", "2"]
	vb.name = "DEBIAN"
    end
   debian.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y git
    apt-get install fish
    apt-get install tmux
    apt-get install mc
    apt-get install git
   SHELL

  end
config.vm.define "alma" do |alma|
  alma.vm.box = "bento/almalinux-9.2"
  alma.vm.network "public_network"
  alma.vm.network "private_network", ip: "192.168.50.54", virtualbox__intnet: "ansible_lab"
  alma.vm.hostname = "alma-kmasing"
  alma.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "2048"]
    vb.customize ["modifyvm", :id, "--cpus", "2"]
	vb.name = "alma"
    end
alma.vm.provision "shell", inline: <<-SHELL
    yum update
    yum install -y git
    yum install fish
    yum install tmux
    yum install mc
    yum install git
   SHELL

  end
end